import "@/assets/styles/globals.css";
import LayoutMain from "@/layouts/main/LayoutMain";
import { Suspense } from "react";
import Loading from "./loading";

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

type Props = {
	children: React.ReactNode;
};

export default function RootLayout({ children }: Props) {
	return (
		<html lang="fr">
			<body>
				<LayoutMain navFixed>
					<Suspense fallback={<Loading />}>{children}</Suspense>
				</LayoutMain>
			</body>
		</html>
	);
}
